### ISSUE TITLE
Clean up quotes database

### ISSUE THREAD

**Issue by XYQuadrat** [markbeep/Lecturfier#92]
Over time, many quotes have accumulated in the database that are neither funny nor otherwise worthy to preserve. Let's go ahead and clean up the database a bit to reduce clutter and keep just the good ones.

If you want to suggest quotes for removal, please add the corresponding IDs as a comment, and I'm certain that @markbeep will eventually get around to deleting them.

**Comment by markbeep** [comment]
This is a great idea. Simply post the quote ID and I'll look into deleting it.

**Comment by xHarlock** [comment]
ID           Reason
525         Never said that
526         Typo, isn't even funny
528         Utterly useless
2694       Useless
2828       Fake quote made by leaving out letters

**Comment by XYQuadrat** [comment]
2596 / content: "@jonas", belongs to non-existing "ping"
2597 / content: "bark", belongs to "dogs" (is slightly funny, but only slightly)
1897 / belongs to non-existing "if" 
1770 / content would be fine, but is misattributed (is from Crazyy)
1958 / content: "link" from non-existing"-the"
1959 / content: link to Rickroll, from non-existing "-the"

**Comment by markbeep** [comment]
Thanks for sending the quoteIDs. I deleted all of the listed ones.

**Comment by XYQuadrat** [comment]
This can now be handled via the built-in report functionality. Closing.
